# Generated by Django 5.1.4 on 2025-04-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionfield',
            name='field_mapping',
        ),
        migrations.AddField(
            model_name='questionfield',
            name='field_mapping',
            field=models.ManyToManyField(to='api.ehrfieldmapping'),
        ),
    ]
