# Generated by Django 5.1.4 on 2025-05-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_questionfield_field_mapping_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ehrsystem',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
