# Generated by Django 5.1.4 on 2025-05-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_ehrsystem_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehrfieldmapping',
            name='field_type',
            field=models.CharField(choices=[('int', 'Integer'), ('float', 'Float'), ('str', 'String'), ('bool', 'Boolean'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'DateTime')], default='str', max_length=20),
        ),
    ]
