# Generated by Django 5.1.4 on 2025-05-06 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ehrfieldmapping_field_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ehrfieldmapping',
            name='field_user_key',
            field=models.BooleanField(default=False),
        ),
    ]
