# Generated by Django 5.1.4 on 2025-05-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_ehrsystem_destination_url_ehrintegrationrecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ehrintegrationrecord',
            old_name='form',
            new_name='form_answer',
        ),
        migrations.RemoveField(
            model_name='ehrintegrationrecord',
            name='retry_count',
        ),
        migrations.RemoveField(
            model_name='ehrintegrationrecord',
            name='success',
        ),
        migrations.AddField(
            model_name='ehrintegrationrecord',
            name='payload',
            field=models.JSONField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ehrintegrationrecord',
            name='response_body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ehrintegrationrecord',
            name='response_status',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ehrintegrationrecord',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
